name: ktr-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - tifffile
  - matplotlib
  - scikit-image
  - pip
  - pip:
      - trackpy
      - cellpose
